export const MOCK_SCENARIO = {
  PAOTANG: {
    SUCCESS: "PT_PASS:SUCCESS",
    INVALID_GRANT: "PT_PASS:INVALID_GRANT",
    SUCCESS_ONCE: "PT_PASS:SUCCESS_ONCE",
  },
  OTP: {
    SUCCESS: "OTP:SUCCESS",
    INVALID: "OTP:INVALID",
  },
  SMS: {
    SUCCESS: "SMS:SUCCESS",
    INVALID_NUMBER: "SMS:INVALID_NUMBER",
    UNAVAILABLE: "SMS:UNAVAILABLE",
  },
  USER: {
    GET_USER_SUCCESS: "USER:GET_USER_SUCCESS",
    GET_USER_INVALID: "USER:GET_USER_INVALID",
  },
  BANK_ACCOUNT: {
    GET_ACCOUNT_NOT_FOUND: "BANK_ACCOUNT:GET_ACCOUNT_NOT_FOUND",
    ACCOUNT_NUMBER_ALREADY_EXISTS: "BANK_ACCOUNT:ACCOUNT_NUMBER_ALREADY_EXISTS",
  },
  EKYC: {
    VERIFY_APPROVED: "EKYC:VERIFY_APPROVED",
    VERIFY_FAILED: "EKYC:VERIFY_FAILED",
  },
  TRANSFER: {
    SUCCESS: "TRANSFER:SUCCESS",
    INSUFFICIENT_AMOUNT: "TRANSFER:INSUFFICIENT_AMOUNT",
    INVALID_ACCOUNT: "TRANSFER:INVALID_ACCOUNT",
    LIST_TRANSFERS: "TRANSFER:LIST_TRANSFERS",
    EMPTY_LIST: "TRANSFER:EMPTY_LIST",
  },
} as const;
