export const MOCK_SCENARIO = {
  PAOTANG: {
    SUCCESS: "PT_PASS:SUCCESS",
    INVALID_GRANT: "PT_PASS:INVALID_GRANT",
    SUCCESS_ONCE: "PT_PASS:SUCCESS_ONCE",
  },
  OTP: {
    SUCCESS: "OTP:SUCCESS",
    INVALID: "OTP:INVALID",
  },
  SMS: {
    SUCCESS: "SMS:SUCCESS",
    INVALID_NUMBER: "SMS:INVALID_NUMBER",
    UNAVAILABLE: "SMS:UNAVAILABLE",
  },
} as const;
